/**
 * Upload generated WebP assets to GitHub Release and update imageUrls.ts.
 * Run AFTER generate-assets.ts:
 *   npx ts-node --project tsconfig.scripts.json scripts/upload-assets.ts
 *
 * Requires: gh CLI authenticated (gh auth status)
 */

import * as fs from 'fs';
import * as path from 'path';
import { execSync } from 'child_process';

const OUT_DIR = path.join(process.cwd(), 'generated-assets');
const RELEASE_TAG = 'game-assets-v2';
const REPO = 'danielzaiser91/anime-adventure';
const CDN_BASE = `https://github.com/${REPO}/releases/download/${RELEASE_TAG}`;

function run(cmd: string): string {
  return execSync(cmd, { encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'] }).trim();
}

function releaseExists(): boolean {
  try {
    run(`gh release view ${RELEASE_TAG} --repo ${REPO}`);
    return true;
  } catch {
    return false;
  }
}

function main() {
  const files = fs.readdirSync(OUT_DIR).filter(f => f.endsWith('.webp'));

  if (files.length === 0) {
    console.error('No .webp files in generated-assets/. Run generate-assets.ts first.');
    process.exit(1);
  }

  console.log(`Found ${files.length} WebP files to upload.`);

  // Create release if needed
  if (!releaseExists()) {
    console.log(`Creating GitHub Release: ${RELEASE_TAG}...`);
    run(`gh release create ${RELEASE_TAG} --repo ${REPO} --title "Game Assets v2 (WebP)" --notes "AI-generated game artwork — WebP, 3 sizes per image." --latest=false`);
    console.log('Release created.');
  } else {
    console.log(`Release ${RELEASE_TAG} already exists — uploading/overwriting files.`);
  }

  // Upload in batches to avoid arg-list limits
  const batchSize = 20;
  for (let i = 0; i < files.length; i += batchSize) {
    const batch = files.slice(i, i + batchSize);
    const filePaths = batch.map(f => `"${path.join(OUT_DIR, f)}"`).join(' ');
    console.log(`Uploading batch ${Math.floor(i / batchSize) + 1}/${Math.ceil(files.length / batchSize)}: ${batch[0]}...`);
    run(`gh release upload ${RELEASE_TAG} ${filePaths} --repo ${REPO} --clobber`);
  }

  console.log('All files uploaded.');

  // Build imageUrls.ts
  const keys = new Set<string>();
  for (const f of files) {
    // e.g. village_dawn_md.webp → village_dawn
    const key = f.replace(/_(?:sm|md|lg)\.webp$/, '');
    keys.add(key);
  }

  const urlMap: Record<string, string> = {};
  for (const key of keys) {
    urlMap[key] = `${CDN_BASE}/${key}_md.webp`;
  }

  const content = `// Generated by scripts/upload-assets.ts — do not edit manually
// CDN: ${CDN_BASE}
export const IMAGE_URLS: Record<string, string> = ${JSON.stringify(urlMap, null, 2)};

export const ASSET_CDN_BASE = '${CDN_BASE}';
`;

  fs.writeFileSync(path.join(process.cwd(), 'src', 'data', 'imageUrls.ts'), content, 'utf8');
  console.log(`\n✅ imageUrls.ts updated with ${keys.size} CDN URLs.`);
  console.log('Next: commit src/data/imageUrls.ts and push to trigger deploy.');
}

main();
